services:
  backend:
    build: ./backend
    container_name: ansible-dashboard-backend
    ports:
      - "8000:8000"
    environment:
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://backend:8000
      - DATABASE_URL=sqlite:///data/database.db
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ansible-dashboard-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
